/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserLoginRouteImport } from './routes/user-login'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIndexRouteImport } from './routes/$category.index'
import { Route as CategoryExamRouteImport } from './routes/$category.$exam'
import { Route as MockTestTestIdExamRouteImport } from './routes/mock-test.$testId.exam'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user-login',
  path: '/user-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoryRoute,
} as any)
const CategoryExamRoute = CategoryExamRouteImport.update({
  id: '/$exam',
  path: '/$exam',
  getParentRoute: () => CategoryRoute,
} as any)
const MockTestTestIdExamRoute = MockTestTestIdExamRouteImport.update({
  id: '/mock-test/$testId/exam',
  path: '/mock-test/$testId/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/notifications': typeof NotificationsRoute
  '/subscription': typeof SubscriptionRoute
  '/user-login': typeof UserLoginRoute
  '/$category/$exam': typeof CategoryExamRoute
  '/$category/': typeof CategoryIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/mock-test/$testId/exam': typeof MockTestTestIdExamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/notifications': typeof NotificationsRoute
  '/subscription': typeof SubscriptionRoute
  '/user-login': typeof UserLoginRoute
  '/$category/$exam': typeof CategoryExamRoute
  '/$category': typeof CategoryIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/mock-test/$testId/exam': typeof MockTestTestIdExamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/notifications': typeof NotificationsRoute
  '/subscription': typeof SubscriptionRoute
  '/user-login': typeof UserLoginRoute
  '/$category/$exam': typeof CategoryExamRoute
  '/$category/': typeof CategoryIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/mock-test/$testId/exam': typeof MockTestTestIdExamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/admin'
    | '/admin-login'
    | '/bookmarks'
    | '/contact'
    | '/dashboard'
    | '/exams'
    | '/notifications'
    | '/subscription'
    | '/user-login'
    | '/$category/$exam'
    | '/$category/'
    | '/auth/google/callback'
    | '/mock-test/$testId/exam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/bookmarks'
    | '/contact'
    | '/dashboard'
    | '/exams'
    | '/notifications'
    | '/subscription'
    | '/user-login'
    | '/$category/$exam'
    | '/$category'
    | '/auth/google/callback'
    | '/mock-test/$testId/exam'
  id:
    | '__root__'
    | '/'
    | '/$category'
    | '/admin'
    | '/admin-login'
    | '/bookmarks'
    | '/contact'
    | '/dashboard'
    | '/exams'
    | '/notifications'
    | '/subscription'
    | '/user-login'
    | '/$category/$exam'
    | '/$category/'
    | '/auth/google/callback'
    | '/mock-test/$testId/exam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  NotificationsRoute: typeof NotificationsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  UserLoginRoute: typeof UserLoginRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  MockTestTestIdExamRoute: typeof MockTestTestIdExamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-login': {
      id: '/user-login'
      path: '/user-login'
      fullPath: '/user-login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/$category/$exam': {
      id: '/$category/$exam'
      path: '/$exam'
      fullPath: '/$category/$exam'
      preLoaderRoute: typeof CategoryExamRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/mock-test/$testId/exam': {
      id: '/mock-test/$testId/exam'
      path: '/mock-test/$testId/exam'
      fullPath: '/mock-test/$testId/exam'
      preLoaderRoute: typeof MockTestTestIdExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CategoryRouteChildren {
  CategoryExamRoute: typeof CategoryExamRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategoryExamRoute: CategoryExamRoute,
  CategoryIndexRoute: CategoryIndexRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRouteWithChildren,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  NotificationsRoute: NotificationsRoute,
  SubscriptionRoute: SubscriptionRoute,
  UserLoginRoute: UserLoginRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  MockTestTestIdExamRoute: MockTestTestIdExamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
